app/urls.py
from django.urls import path

from app import views

urlpatterns = [
    path("", views.ShowBooksView.as_view(), name="index"),
    path("authors", views.ShowAuthorView.as_view(), name="authors"),
    path("authors_list", views.AuthorListView.as_view(), name="authors_list"),
    path(
        "create_author", views.CreateAuthorView.as_view(), name="create_author"
    ),
    path("create_book", views.CreateBookView.as_view(), name="create_book"),
    path(
        "detail_book/<int:pk>",
        views.DetailBookView.as_view(),
        name="detail_book",
    ),
    path(
        "delete_author/<int:pk>",
        views.DeleteAutherView.as_view(),
        name="delete_author",
    ),
    path(
        "delete_book/<int:pk>",
        views.DeleteBookView.as_view(),
        name="delete_book",
    ),
    path(
        "show_authors_books/<int:pk>",
        views.show_authors_books,
        name="show_authors_books",
    ),
    path(
        "update_author/<int:pk>",
        views.UpdateAuthorView.as_view(),
        name="update_author",
    ),
    path(
        "update_book/<int:pk>",
        views.UpdateBookView.as_view(),
        name="update_book",
    ),
]

books/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include
from django.urls import path

urlpatterns = [
    path("", include("app.urls")),
    path("admin/", admin.site.urls),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/models.py
from django.db import models


class Book(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField(blank=True)
    image = models.ImageField(upload_to="app/images", blank=True)
    author = models.ManyToManyField("Author", related_name="books")

    def __str__(self):
        return self.title


class Author(models.Model):
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)

    def __str__(self):
        return f"{self.first_name} {self.last_name}"

app/views.py
from typing import Any

from django.http import HttpResponse
from django.shortcuts import render
from django.views import generic

from .models import Author
from .models import Book


class ShowBooksView(generic.ListView):
    template_name = "app/index.html"
    model = Book
    context_object_name = "books"


class DetailBookView(generic.DetailView):
    template_name = "app/detail_book.html"
    model = Book


class DeleteBookView(generic.DeleteView):
    template_name = "app/delete_book.html"
    model = Book
    success_url = "/"


class UpdateBookView(generic.UpdateView):
    template_name = "app/update_book.html"
    model = Book
    fields = "__all__"
    success_url = "/"

    def get_context_data(self, **kwargs: Any) -> dict[str, Any]:
        contex = super().get_context_data()
        contex["authors"] = Author.objects.all()
        return contex


class CreateBookView(generic.CreateView):
    template_name = "app/create_book.html"
    model = Book
    fields = "__all__"
    success_url = "/"

    def get_context_data(self, **kwargs: Any) -> dict[str, Any]:
        contex = super().get_context_data()
        contex["authors"] = Author.objects.all()
        return contex


class ShowAuthorView(generic.ListView):
    template_name = "app/authors.html"
    model = Author
    context_object_name = "authors"


class CreateAuthorView(generic.CreateView):
    template_name = "app/create_author.html"
    model = Author
    fields = "__all__"
    success_url = "/authors"


class UpdateAuthorView(generic.UpdateView):
    template_name = "app/update_author.html"
    model = Author
    fields = "__all__"
    success_url = "/authors"


class DeleteAutherView(generic.DeleteView):
    template_name = "app/delete_author.html"
    model = Author
    success_url = "/authors"


class AuthorListView(generic.ListView):
    template_name = "app/authors_list.html"
    model = Author
    context_object_name = "authors"


def show_authors_books(request, pk: int) -> HttpResponse:
    books = Book.objects.filter(author=pk)
    return render(request, "app/show_authors_books.html", {"books": books})

app/templates/app/authors.html
{% extends 'app/base.html' %}

{% load static %}

{% block content %}
<hr>
<div class="row justify-content-center mt-5" style="position: relative;">
    <div class="col-md-10" style="display: inline-flex;">
        <h1> Автор</h1>

        <form action="{% url 'create_author' %}" style="position: absolute; right: 0;">
        <button type="submit" class="btn btn-info" >Добавить</button>
        </form>
    </div>
</div>
<hr>
{% if authors %}
{% for author in authors %}
<div class="row justify-content-center mt-4" style="position: relative;">
             <div class="col-md-9">
                 <h7>{{ author }}</h7>
             </div>
            <div class="col-md-4" style="position: absolute; right: 0;">
                <form action="{% url 'update_author' author.pk %}"
                      style="display: inline-block">
                    <button class="btn btn-link" type="submit">
                        Изменить
                    </button>
                </form>
                <form action="{% url 'delete_author' author.pk %}"
                      style="display: inline-block">
                    <button class="btn btn-link" type="submit">
                        Удалить
                    </button>
                </form>
            </div>
        </div>
<hr>
{% endfor %}
{% else %}
<h3>Пока нет ни одного автора</h3>
{% endif %}

{% endblock %}

app/templates/app/authors_list.html
{% extends 'app/base.html' %}

{% load static %}

{% block content %}
<hr>
<div class="row justify-content-center mt-5" style="position: relative;">
    <div class="col-md-10">


    </div>
</div>
<h1> Авторы</h1>
  <br>
{% if authors %}
<ul class="list-group">
{% for author in authors %}
<a href="{% url 'show_authors_books' author.pk %}">
<li class="list-group-item d-flex justify-content-between align-items-center">{{ author }}
  <span class="badge bg-primary rounded-pill">Книг: {{ author.books.all|length }}</span>
</li>
</a>


{% endfor %}
</ul>
{% else %}
<h3>Пока нет ни одного автора</h3>
{% endif %}


{% endblock %}

app/templates/app/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    
    <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
  <link rel="icon" type="image/png" href="{% static 'app/icon.png' %}">

  <link href="https://fonts.googleapis.com/css?family=Lato&display=swap" rel="stylesheet">
    <title>Книги</title>
  </head>
  <body >
    <nav id="topNav" class="navbar navbar-expand-md navbar-light">
    <div class="container">
      <a class="navbar-brand" href="{% url 'index' %}">
        <img src="{% static 'app/icon.png' %}" width="30" height="30" class="d-inline-block align-top" alt="Dmitry's Logo">
        <span>Книги</span>
      </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div>
        <ul class="navbar-nav ml-auto">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'authors_list' %}">Авторы</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'index' %}">Книги</a>
          </li>
        </ul>
      </div>
      <div class="collapse navbar-collapse text-center" id="navbarNav">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'authors' %}">Добавить автора</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'create_book' %}">Добавить книгу</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>
  <div class="container">
    {% block content %}{% endblock %}
  </div>

  <!-- Optional JavaScript -->
  <!-- jQuery first, then Popper.js, then Bootstrap JS -->
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
  <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
</body>

</html>

app/templates/app/create_author.html
{% extends 'app/base.html' %}

{% load static %}

{% block content %}
<hr>

<a href="{% url 'authors' %}"><-Назад</a>
<div class="card" style="display: flex; justify-content: center;">
    <div class="row g-0" style="display: flex; justify-content: center;">
        <div class="col-md-5" >
            <div class="card-body">

                    {% if error %}
                    <div class="alert alert-danger" role="alert">
                        {{ error }}
                    </div>
                    {% endif %}
                    <h3>Добавить автора</h3>
                    <br>
                    <form method="POST" >
                        {% csrf_token %}
                        <div class="form-group">
                            <label for="first_name"><h5>Имя</h5></label>
                            <input type="text" name="first_name" class="form-control"
                                   id="first_name"
                                   value="{{ author.first_name }}" required>
                        </div>
                        <div class="form-group">
                            <label for="last_name"><h5>Фамилия</h5></label>
                            <input type="text" name="last_name" class="form-control"
                                   id="last_name"
                                   value="{{ author.last_name }}" required>
                        </div>
                        <br>
                        <button type="submit" class="btn btn-primary">
                            Сохранить
                        </button>
                    </form>
            </div>
        </div>
    </div>
</div>

{% endblock %}

app/templates/app/create_book.html
{% extends 'app/base.html' %}

{% load static %}

{% block content %}
<hr>
<a href="{% url 'index' %}"><-Назад</a>
<div class="card" style="display: flex; justify-content: center;">
    <div class="row g-0" style="display: flex; justify-content: center;">
        <div class="col-md-6">
            <div class="card-body">
                {% if error %}
                <div class="alert alert-danger" role="alert">
                    {{ error }}
                </div>
                {% endif %}
                <h3>Добавить книгу</h3>
                <br>
                <form method="POST" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="form-group">
                        <label for="title"><h5>Заголовок</h5></label>
                        <input type="text" name="title" class="form-control"
                               id="title"
                               value="{{ book.title }}" size="600" required>
                    </div>
                    <div class="form-group">
                        <label for="description"><h5>Описание</h5></label>
                        <textarea name="description" rows="5"
                                  class="form-control" id="description">{{ book.description }}</textarea>
                    </div>
                    <div class="form-group">
                        <label for="id_image"><h5>Выбрать изображение</h5>
                        </label>
                        <input type="file" name="image" accept="image/*"
                               id="id_image">
                    </div>
                    <br>
                    <div class="form-group">
                        <label for="id_author" style="margin-right: 10px;">
                            <h5>Автор:</h5></label>
                        <select name="author" required="" id="id_author"
                                multiple=""
                                style="padding-left: 5px; padding-right: 10px; padding-bottom: 5px;">
                            {% for author in authors %}
                            <option value="{{ author.pk }}">{{ author }}
                            </option>
                            {% endfor %}
                        </select>
                        <a style="margin-left:10px;"
                           href="{% url 'authors'%}">Редактировать</a>
                    </div>
                    <br>
                    <button type="submit" class="btn btn-primary">
                        Сохранить
                    </button>
                </form>
            </div>
        </div>
    </div>
</div>

{% endblock %}

app/templates/app/delete_author.html
{% extends 'app/base.html' %}

{% load static %}

{% block content %}
<hr>

<a href="{% url 'authors' %}"><-Назад</a>
<div class="card" style="display: flex; justify-content: center;">
    <div class="row g-0" style="display: flex; justify-content: center;">
        <div class="col-md-5" >
            <div class="card-body">

                    {% if error %}
                    <div class="alert alert-danger" role="alert">
                        {{ error }}
                    </div>
                    {% endif %}
                    <h3>Удалить автора?</h3>
                    <br>
                    <form method="POST" >
                        {% csrf_token %}
                        <div class="form-group">
                            <label ><h5>{{ author.first_name }} {{ author.last_name }}</h5></label>
                        </div>
                        <button type="submit" class="btn btn-danger">
                            Удалить
                        </button>
                    </form>
            </div>
        </div>
    </div>
</div>

{% endblock %}

app/templates/app/delete_book.html
{% extends 'app/base.html' %}

{% load static %}

{% block content %}
<hr>
<h3 style="color: red">Вы действительно хотите удалить эту книгу?</h3>
<div class="card" style=" display: flex; justify-content: center;">

  <div class="row g-0">
    <div class="col-md-4">
      <img src="{{ book.image.url }}" class="img-fluid rounded-start" alt="..." >
    </div>
    <div class="col-md-8">
      <div class="card-body">
        <h5 class="card-title">{{ book.title }}</h5>
          Автор:
          {% for author in book.author.all %}
            <li><small class="text-muted">{{ author }}</small></li>
          {% endfor %}
        <br>
        <p class="card-text">{{ book.description }}</p>
      </div>
        <div style="display: flex; ">
        <form action="{% url 'detail_book' book.pk %}" style="margin: 4px;">
            <button class="btn btn-outline-primary" >Отмена</button>
        </form>
        <form method="post" style="margin: 4px;">
            {% csrf_token %}
            <button class="btn btn-outline-danger" >Удалить</button>
        </form>
        </div>
       </div>
  </div>
</div>

{% endblock %}

app/templates/app/detail_book.html
{% extends 'app/base.html' %}

{% load static %}

{% block content %}
<hr>
<a href="{% url 'index' %}"><-Назад</a>
<div class="card" style=" display: flex; justify-content: center;">
  <div class="row g-0">
    <div class="col-md-4">
      {% if book.image %}
            <img src="{{ book.image.url }}" class="img-fluid rounded-start"
                 alt="...">
            {% else %}
            <img src="{% static 'app/nofoto.jpg' %}" class="card-img-top" alt="..."
                 width="200" height="400">
            {% endif %}
    </div>
    <div class="col-md-8">
      <div class="card-body">
        <h5 class="card-title">{{ book.title }}</h5>
          Автор:
          {% for author in book.author.all %}
            <li><small class="text-muted">{{ author }}</small></li>
          {% endfor %}
        <br>
        <p class="card-text">{{ book.description }}</p>
      </div>
        <div style="display: flex; ">
        <form action="{% url 'update_book' book.pk %}" style="margin: 4px;">
            <button class="btn btn-outline-primary" >Редактировать</button>
        </form>
        <form action="{% url 'delete_book' book.pk%}" style="margin: 4px;">
            <button class="btn btn-outline-danger" >Удалить</button>
        </form>
        </div>
       </div>
  </div>
</div>
<br>
{% endblock %}

app/templates/app/index.html
{% extends 'app/base.html' %}

{% load static %}

{% block content %}
<hr>

<div class="row" style="display: flex; justify-content: center;">
    {% if books %}
    {% for book in books %}
    <div class="card" style="width: 16rem; margin: 10px; padding: 4px;">
        <a href="{% url 'detail_book' book.pk %}">
        {% if book.image %}
            <img src="{{ book.image.url }}" class="card-img-top" alt="..."
                 width="200" height="400">
            {% else %}
            <img src="{% static 'app/nofoto.jpg' %}" class="card-img-top" alt="..."
                 width="200" height="400">
            {% endif %}

            <div class="card-body">
                <h5 class="card-title">{{ book.title }}</h5>
        </a>
        Автор:
        {% for author in book.author.all %}
        <li><small class="text-muted">{{ author }}</small></li>
        {% endfor %}
        <br>
        <p class="card-text">{{ book.description|truncatechars:50 }}</p>
    </div>
</div>
{% endfor %}

</div>

{% else %}
<h3>Пока нет ни одной книги</h3>
{% endif %}
<br>

{% endblock %}

app/templates/app/show_authors_books.html
{% extends 'app/base.html' %}

{% load static %}

{% block content %}
<hr>

<div class="row" style="display: flex; justify-content: center;">
    {% if books %}
    {% for book in books %}
    <div class="card" style="width: 16rem; margin: 10px; padding: 4px;">
        <a href="{% url 'detail_book' book.pk %}">
        {% if book.image %}
            <img src="{{ book.image.url }}" class="card-img-top" alt="..."
                 width="200" height="400">
            {% else %}
            <img src="{% static 'app/nofoto.jpg' %}" class="card-img-top" alt="..."
                 width="200" height="400">
            {% endif %}

            <div class="card-body">
                <h5 class="card-title">{{ book.title }}</h5>
        </a>
        Автор:
        {% for author in book.author.all %}
        <li><small class="text-muted">{{ author }}</small></li>
        {% endfor %}
        <br>
        <p class="card-text">{{ book.description|truncatechars:50 }}</p>
    </div>
</div>
{% endfor %}

</div>

{% else %}
<h3>Пока нет ни одной книги</h3>
{% endif %}
{% endblock %}

app/templates/app/update_author.html
{% extends 'app/base.html' %}

{% load static %}

{% block content %}
<hr>

<a href="{% url 'authors' %}"><-Назад</a>
<div class="card" style="display: flex; justify-content: center;">
    <div class="row g-0" style="display: flex; justify-content: center;">
        <div class="col-md-5" >
            <div class="card-body">

                    {% if error %}
                    <div class="alert alert-danger" role="alert">
                        {{ error }}
                    </div>
                    {% endif %}
                    <h3>Редактировать</h3>
                    <br>
                    <form method="POST" >
                        {% csrf_token %}
                        <div class="form-group">
                            <label for="first_name"><h5>Имя</h5></label>
                            <input type="text" name="first_name" class="form-control"
                                   id="first_name"
                                   value="{{ author.first_name }}" required>
                        </div>
                        <div class="form-group">
                            <label for="last_name"><h5>Фамилия</h5></label>
                            <input type="text" name="last_name" class="form-control"
                                   id="last_name"
                                   value="{{ author.last_name }}" required>
                        </div>
                        <br>
                        <button type="submit" class="btn btn-primary">
                            Сохранить
                        </button>
                    </form>
            </div>
        </div>
    </div>
</div>

{% endblock %}

app/templates/app/update_book.html
{% extends 'app/base.html' %}

{% load static %}

{% block content %}

<hr>
<a href="{% url 'detail_book' book.pk %}"><-Назад</a>
<div class="card" style=" display: flex; justify-content: center;">
    <div class="row g-0">
        <div class="col-md-4" style="margin-right: 30px;">
            {% if book.image %}
            <img src="{{ book.image.url }}" class="img-fluid rounded-start"
                 alt="...">
            {% else %}
            <img src="{% static 'app/nofoto.jpg' %}" class="card-img-top"
                 alt="..."
                 width="200" height="400">
            {% endif %}
        </div>
        <div class="col-md-6">
            <div class="card-body">
                {% if error %}
                <div class="alert alert-danger" role="alert">
                    {{ error }}
                </div>
                {% endif %}
                <form method="POST" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="form-group">
                        <label for="title"><h5>Заголовок</h5></label>
                        <input type="text" name="title" class="form-control"
                               id="title"
                               value="{{ book.title }}" required>
                    </div>
                    <div class="form-group">
                        <label for="description"><h5>Описание</h5></label>
                        <textarea name="description" rows="5"
                                  class="form-control" id="description">{{ book.description }}</textarea>
                    </div>
                    <div class="form-group">
                        <label><h5>Изображение сейчас:</h5></label>
                        <label>{{ book.image }} </label>
                    </div>
                    <div class="form-group">
                        <label for="id_image"><h5>Изменить изображение</h5>
                        </label>
                        <input type="file" name="image" accept="image/*"
                               id="id_image">
                    </div>
                    <br>
                    <div class="form-group">
                        <h5><label for="id_author" style="margin-right: 10px;">
                            Автор:</label></h5>
                        <select name="author" required="" id="id_author"
                                multiple=""
                                style="padding-left: 5px; padding-right: 10px; padding-bottom: 5px;">
                            {% for author in authors %}
                            {% if author in book.author.all %}
                            <option value="{{ author.pk }}" selected>{{ author }}
                            </option>
                            {% else %}
                            <option value="{{ author.pk }}">{{ author }}
                            </option>
                            {% endif %}
                            {% endfor %}
                        </select>
                        <a style="margin-left:10px;"
                           href="{% url 'authors'%}">Редактировать</a>
                    </div>
                    <br>
                    <button type="submit" class="btn btn-primary">
                        Сохранить
                    </button>
                </form>
            </div>
        </div>
    </div>
</div>

{% endblock %}